-----------------------------
--"EMPLOYEE"
-----------------------------
CREATE TABLE "EMPLOYEE" (
	"EMPLOYEE_ID" NUMERIC(6) PRIMARY KEY,
	"E_FIRST_NAME" CHAR(50) NOT NULL,
	"E_MIDDLE_INTIAL" CHAR(50) NOT NULL,
	"E_LAST_NAME" CHAR(50) NOT NULL,
	"GENDER" CHAR(15) NOT NULL,
	"HIRE_DATE" DATE NOT NULL,
	"SUPERVISOR_ID" NUMERIC(6)
	)