--DROP TABLE
--DROP TABLE "PERFORMANCE_RATING";
--DROP TABLE "PERFORMANCE_REVIEW";
--DROP TABLE "EMPLOYEE";
--DROP TABLE "PAY_HISTORY";
--DROP TABLE "POSITION_HISTORY";
--DROP TABLE "POSITION";
--DROP TABLE "TEAM";
--DROP TABLE "DEPARTMENT";
--DROP TABLE "BUDGET";
--DROP TABLE "PROJECTIONS";

-----------------------------
--"PERFORMANCE_RATING"
-----------------------------
CREATE TABLE "PERFORMANCE_RATING" (
	"P_RATING_ID" VARCHAR(3) PRIMARY KEY,
	"P_RATING_NAME" VARCHAR(30) NOT NULL,
	"P_RATING_DESCRIPTION" VARCHAR(500) NOT NULL,
	"MG_LOWER_BOUND" DECIMAL(10,5) NOT NULL,
	"MG_TARGET" DECIMAL(10,5) NOT NULL,
	"MG_UPPER_BOUND" DECIMAL(10,5) NOT NULL
	)