-----------------------------
--"PROJECTIONS"
-----------------------------
CREATE TABLE "PROJECTIONS" (
	"EMPLOYEE_ID" NUMERIC(6) NOT NULL,
	"DATE_OF_PROJECTION" DATE NOT NULL,
	"PR_PROJECTION" VARCHAR(3),
	"SALARY_INCREASE_PROJECTION" NUMERIC(10,5),
	PRIMARY KEY("EMPLOYEE_ID", "DATE_OF_PROJECTION")
	)